### ISSUE TITLE
arc/contractAddresses.json should come from the @daostack/migration package

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/DAOcreator#100]
Currently we have a "hard coded" set of contract addresses for Arc, and we should instead be pulling the latest from DAOstack's migration repo (@daostack/migration/migration.json). That way when they redeploy things, we get updated.

This is also a partial solution because it requires us to redeploy our app whenever they update the protocol. I see three categories we should handle:
1. Base Contracts (ex: GEN, UController, etc)
2. Schemes & Constraints (ex: TokenCapGC, GenericScheme, etc)
3. Voting Machines (ex: AbsoluteVote, GenesisProtocol, etc)

I see the ideal situation looking like:
- Schemes, Constraints, and Voting Machines' addresses are all read from an on-chain registry.
- Base Contracts' addresses could come from an on-chain registry. In the short term this can be managed by a simple mult-sig (DAOstack, dOrg, and anyone else developing on the platform), and can eventually be decentralized when it's been hardened.

Thoughts?

**Comment by sogasg** [comment]
I have some concerns about being "auto-updated":
- What if the contract interface changes?
- I think we should vet the addresses we use.
- We having to do this manually provides one more safety net.

I think we should focus on the ideal situation (the on.chain registry). At least for Schemes, Constraints, and Voting Machines.

When it comes to the Base Contracts, I am uncertain. But I think the best solution is to have it "hardcoded". And maybe have advanced settings where users can change it?

**Comment by dOrgJelli** [comment]
Yes I definitely agree. As for interface changes, it'd be nice to have some form of guarantee that minor updates didn't change this, and major updates that were breaking were easily detectable.

Think of a contract registry that, when an entry is changed, it validates the interface is consistent.
