### ISSUE TITLE
Able to add feature twice

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/DAOcreator#102]
You're currently able to add features twice, for example "Contribution Reward".

**Comment by sogasg** [comment]
This is a feature not a bug 😆😛

But it might not make sense for every scheme. What schemes should be restricted?

**Comment by dOrgJelli** [comment]
I'm really not sure, what schemes does this make sense for @sogasg?

**Comment by sogasg** [comment]
I think it definitely makes sense for the GenericScheme.

Also, it might make sense for a DAO to have multiple ContributionReward schemes (for instance a  fast-paced voting machine for "small everyday tasks" and a slow one for team grants).

It might also make sense to have multiple OrganizationRegister (one for restaurants and one for javascript contractors).

Anyway, we should probably add an attribute to the schemes (https://github.com/dOrgTech/DAOcreator/blob/dev/src/lib/integrations/daoStack/arc/schemes.ts) for indication if there can be more then one. And filter that on the select scheme menu.
