### ISSUE TITLE
Changing Browser Focus During Deployment Breaks Deployment

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/DAOcreator#104]
When deploying the DAO, if you're in the middle of a step (ex: 3), and switch window focus (focus something other than your browser), after the transaction clears the application stays waiting.

**Comment by dOrgJelli** [comment]
This has happened a few times, and I'm not sure why... it's almost like the await is getting permanently stalled and never updated again.

**Comment by sogasg** [comment]
I can't reproduce this, it's working for me.
