### ISSUE TITLE
Support saving/continuing a setup that's in progress

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/DAOcreator#11]
Support users leaving midway, and wanting to continue where they left off in the setup process. Possible implementation might look like:
- user close tab
- state gets saved in local storage
- when users come back to the site, we look for a saved state and ask if they want to resume if one is found

**Comment by dOrgJelli** [comment]
The state that gets saved should consist of:
- [current step](https://github.com/dOrgTech/DAOcreator/blob/a468a99bb71a36766c6333a3a41b7d347abf7154/src/components/pages/DAOcreator/index.tsx#L26)
- [DAO's form](https://github.com/dOrgTech/DAOcreator/blob/a468a99bb71a36766c6333a3a41b7d347abf7154/src/components/pages/DAOcreator/index.tsx#L40)

For serializing the DAO's form, I would suggest turning it into the [backing state object](https://github.com/dOrgTech/DAOcreator/blob/a468a99bb71a36766c6333a3a41b7d347abf7154/src/lib/forms/dao/DAOForm.ts#L27) and serializing that to JSON. Then when it gets deserialized, just use the [`fromState` method](https://github.com/dOrgTech/DAOcreator/blob/a468a99bb71a36766c6333a3a41b7d347abf7154/src/lib/forms/dao/DAOForm.ts#L35) to get the form back.

**Comment by mrrobot16** [comment]
Checkout this PR: https://github.com/dOrgTech/DAOcreator/pull/222
where i have implemented this feature.

**Comment by dOrgJelli** [comment]
Awesome work @mrrobot16 and @namesty!
