### ISSUE TITLE
Portis integration as an alternative web3 provider

### ISSUE THREAD

**Issue by gh1dra** [dOrgTech/DAOcreator#116]
https://github.com/curved-ethdenver/curve-bonded-crowdfunding/blob/a00477a0c337d921cdc93d186f3132b08887bfdb/src/utils/getPortisWeb3.js

**Comment by gh1dra** [comment]
https://github.com/curved-ethdenver/curve-bonded-crowdfunding/blob/a00477a0c337d921cdc93d186f3132b08887bfdb/src/utils/getPortisWeb3.js

**Comment by orishim** [comment]
this will be taken care of by #223
