### ISSUE TITLE
Make it possible to add more founders

### ISSUE THREAD

**Issue by sogasg** [dOrgTech/DAOcreator#130]
See: https://github.com/daostack/migration/blob/d3f7d44f92740cd84c6643be585682c5c8fc3582/migrate-dao.js#L123

**Comment by oshimony** [comment]
Is there currently a limit on number of founders?

**Comment by sogasg** [comment]
I am not sure, we have to investigate.

This issue was inspired by this PR: https://github.com/daostack/migration/pull/116/files

In this PR a `foundersBatchSize` variable is introduced. `foundersBatchSize` is used to determine the number of founders to add at a time. First via the `forgOrg` function (when "forging" the DAO), then the rest of the founders is added in batch via the `addFounders` function.

**Comment by dOrgJelli** [comment]
This code is just adding N number of founders at a time, and doesn't introduce a limit on how many founders you can have.
