### ISSUE TITLE
Export/Save Deployment Transactions

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/DAOcreator#132]
@leviadam made a request that we support exporting and saving the transactions at the final step. @leviadam & @sogasg, your thoughts?

**Comment by dOrgJelli** [comment]
# Implementation Details
## Getting Tx Data
### Tx Methods
```
const abi = fs.read("./myContract.abi")
const methodName = "foo"
const argValues = [ "string", 12345, "0x123123..." ]
const methodDecl = abi.abi.filter((json) => json.name == methodName)
const txData = web3.eth.abi.encodeFunctionCall(methodDecl, argValues)
```
[reference](https://github.com/zanawar/eth-transaction-proxy/blob/731f526e1189e98dde9f6cadfc0a99168e2679d2/src/lib/internal/EncodeFunctionCall.ts#L3)

### Constructors
```
const abi = fs.read("./myContract.abi")
const methodName = "constructor"
const argValues = [ "string", 12345, "0x123123..." ]
const contract = new web3.eth.Contract(abi)
const deployObject = contract.deploy({
  data: abi.bytecode,
  arguments: argValues
})
const txData = deployObject.encodeABI()
```
[reference](https://github.com/zanawar/eth-transaction-proxy/blob/731f526e1189e98dde9f6cadfc0a99168e2679d2/src/lib/internal/EncodeConstructorCall.ts#L3)

## Forming Tx Payload
```
const tx = {
  from: "0x...",
  to: "0x...", // may be null
  data: txData
}

const txPayload = {
  from: tx.from,
  to: tx.to,
  data: tx.data,
  nonce: web3.eth.getTransactionCount(fromAccount),
  gasPrice: web3.eth.getGasPrice(),
  gasLimit: web3.eth.estimateGas(tx)
}
```
[reference](https://github.com/zanawar/eth-transaction-proxy/blob/731f526e1189e98dde9f6cadfc0a99168e2679d2/src/lib/TransactionProxy.ts#L86)

## Signing Payload
[`web3.eth.accounts.signTransaction(...)`](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethsendtransaction)
[`web3.eth.sendTransaction(...)`](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethsendtransaction)

**Comment by oshimony** [comment]
It should also let the user export the migration.json file that is outputted upon deployment.
https://github.com/daostack/migration.

**Comment by dOrgJelli** [comment]
> It should also let the user export the migration.json file that is outputted upon deployment.
> https://github.com/daostack/migration.

Agreed, and made this issue to track this: https://github.com/dOrgTech/DAOcreator/issues/137

**Comment by dOrgJelli** [comment]
Closing as I don't think this should be added. Exporting the params.json is enough (and better) IMO.

**Comment by orishim** [comment]
@dOrgJelli isn't it still important to export the migration result object with all the addresses of the different contracts deployed? Or is there a separate issue for this?
