### ISSUE TITLE
Initialize Web3 at Review & Deploy step

### ISSUE THREAD

**Issue by orishim** [dOrgTech/DAOcreator#135]
Currently Web3 is initialized and metamask requests a connection after hitting "Create a DAO". Usability might improve if we moved this check to the last possible step before web3 is actually needed (Review & Deploy).

This would make it quicker for users to mess around with the app before fumbling around with passwords, wallets, chrome extensions, etc.

**Comment by sogasg** [comment]
As it is today, you get an error. A user can dismiss the error and continue. But the user will not get farther then the founders page without a address to use as founder (this might be solved by #111 ).

Perhaps it would be better to make a friendlier error/warning message, informing the user that it's possible to continue by dismissing the message, but it will not be possible to deploy them DAO.

I think that it is essential that the user knows at the start that it won't be possible to complete the process (deploy the DAO).

**Comment by dOrgJelli** [comment]
complete.
