### ISSUE TITLE
Use @daostack/migration Package For DAO Deployment

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/DAOcreator#139]
Currently we're deploying DAOs manually (see `src/lib/integrations/daostack/arc/createDAO.ts`). I propose we use the @daostack/migration package instead. This would (1) avoid code duplication (2) reinforce core components of the stack (3) provide more functionality not currently supported in DAOcreator.

https://github.com/daostack/migration

**Comment by sogasg** [comment]
I agree that would be great :)

However, we have to make some contributions to the migration-package first:

- Each scheme is  "hardcoded" while we make it possible to add schemes only by providing a SchemeDefinition. It would be great if the migration script could take in a set of SchemeDefinitions as input (https://github.com/dOrgTech/DAOcreator/blob/dev/src/lib/integrations/daoStack/arc/schemes.ts).
- That means that for now, the migration-package only support schemes that are "hardcoded" in. I think it should be possible for us to also add other schemes.
- The migration-package script is waiting for every transaction before sending the next (some transactions can happen in parallel) so it can take many X more time to deploy with there script.
- The migration-package script does not support "voting machines per scheme".
- No callback for using the DAO's parameters in the schemes (https://github.com/dOrgTech/DAOcreator/blob/bd87369486919fbd082bbd35b517fe155ce5d832/src/lib/integrations/daoStack/arc/schemes.ts#L142)

This is just a quick overview, there might be more.


But if we contribute this thing to the migration-package, it would be great not to need to maintain two versions of this :D

**Comment by orishim** [comment]
Done
https://github.com/dOrgTech/DAOcreator/pull/210
