### ISSUE TITLE
Separate dOrg landing page into different repo

### ISSUE THREAD

**Issue by orishim** [dOrgTech/DAOcreator#142]

**Comment by dOrgJelli** [comment]
@alarivan is working on this at the moment.

**Comment by orishim** [comment]
What is the status of the loading issue?

**Comment by dOrgJelli** [comment]
Waiting on this PR: https://github.com/daostack/migration/pull/247

**Comment by orishim** [comment]
PR is merged but the loading issue persists: https://dorg.netlify.com/.

Does dependency data in the package need to be updated?

**Comment by dOrgJelli** [comment]
Sorry I should have been more specific. That PR means the DAOcreator Lib package can be updated with the optimized contracts folder, then after that’s updated the DAOcreator version the landing page uses can be updated. I went about updating the DAOcreator the others day, but had to PR in another fix to Migration. Will finish this up first thing in the new year when’s I’m back on my computer.

**Comment by dOrgJelli** [comment]
This is finished, landing page repo is here:
https://github.com/dorgtech/landing-page

And it's being served from netlify at dorg.tech.
