### ISSUE TITLE
It should be possible to resubmit a failing transaction

### ISSUE THREAD

**Issue by sogasg** [dOrgTech/DAOcreator#153]
Currently when a transaction fails (is dropped due to too low Gas price etc.) the deployment fails and the DAOcreator wizard needs to be restarted from the beginning.

Even if 3 of 4 transactions goes through, but the 4th fails, the user needs to go through the whole process again and also submitting the successful transactions again.

There should be a button or something that lets the user re-send a transaction. Perhaps the button could show up on the "transaction waiting"- dialog if the transaction takes to much time or something?

**Comment by orishim** [comment]
Subsumed under [200](https://github.com/dOrgTech/DAOcreator/issues/200)
