### ISSUE TITLE
Add Warning For Alchemy Unsupported Voting Machines

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/DAOcreator#157]
When a user makes design decisions that aren't supported by Alchemy, give the user a big red error, letting them know this will make the DAO unusable in Alchemy.

Things that should do this are:
- Selecting a voting machine that isn't Genesis Protocol.
  - "Warning: You've selected a voting machine that's currently unsupported by Alchemy"
- Selecting a scheme that isn't supported by Alchemy.
  - "Warning: You've selected a scheme that isn't currently supported by Alchemy"
- Creating a DAO that doesn't have a SchemeRegistrar scheme.
  - "Warning: We suggest adding a SchemeRegistrar scheme to your DAO. This allows you to add to and modify your DAO's schemes."

**Comment by dOrgJelli** [comment]
See: https://github.com/dOrgTech/DAOcreator/blob/41640bcea1dcdc1a0a0005bd8b361eaa49e28eab/src/components/pages/DAOcreator/SchemesStep/AddSchemeDialog.tsx#L421

**Comment by orishim** [comment]
How about we hide these unless the user selects advanced mode?
[161](https://github.com/dOrgTech/DAOcreator/issues/161)

**Comment by dOrgJelli** [comment]
I like this approach

**Comment by dOrgJelli** [comment]
@cryptogoth description has been updated

**Comment by dOrgJelli** [comment]
Unsupported voting machines have been removed for the time being. Closing this issue.
