### ISSUE TITLE
Import dao-params.json and skip ahead to "Review" step

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/DAOcreator#159]
Import a dao-params.json file at the start so you can skip ahead. An example json file: https://github.com/dOrgTech/dOrgDAO/blob/master/dao-params.json

**Comment by mrrobot16** [comment]
questions:
- In the example JSON for dao params we have five schemes (in the UI there are three) do you want to accept these five or just the three that are in the UI
- For the voting machine params, in the example JSON there is only one object of this. Do we want this params to be global for all the schemes that has been added or let the user the option to add voting machine params for every scheme?

**Comment by mrrobot16** [comment]
**What text shall we define in the dialog box?**

![Screen Shot 2019-09-09 at 12 40 20 PM](https://user-images.githubusercontent.com/761735/64549604-0bebb180-d2ff-11e9-89bf-58631ac4675c.png)

**Comment by dOrgJelli** [comment]
I think we should say something along the lines of "Import an existing dao-params.json file."

**Comment by dOrgJelli** [comment]
Closed via https://github.com/dOrgTech/DAOcreator/pull/184
