### ISSUE TITLE
Simple Mode

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/DAOcreator#161]
Make the current hyper configurable UI the "advanced mode", and provide a simple mode by default that only let's the user configure: details (name, token, etc), founders, contribution reward, scheme registrar.

**Comment by cryptogoth** [comment]
This seems like a bigger task that is blocking #157 . Can we break it up? I was thinking something like:
* put a toggle / button somewhere for "Advanced Mode"
* a boolean React prop gets passed through all the pages called `isAdvancedMode`
* this prop can be used to conditionally render components on each page
* create a new issue for each of the advanced mode changes beyond the simple mode configs listed above.

**Comment by dOrgJelli** [comment]
Hey @cryptogoth, I think we can add warnings without having simple mode. The warnings would be added to the scheme modification page when you're selecting a voting machine that isn't supported by Alchemy (anything that isn't Genesis), or when you select a scheme that isn't supported by alchemy. Also we might want to give a warning when someone creates a DAO that doesn't have a ContributionReward or a SchemeRegistrar scheme.

Sorry this is scattered info, I'll add it to the task's description.

**Comment by orishim** [comment]
I think this is covered by [187](https://github.com/dOrgTech/DAOcreator/issues/187).

Can we close?
