### ISSUE TITLE
Add 'report bug' / 'feature request' button.

### ISSUE THREAD

**Issue by orishim** [dOrgTech/DAOcreator#176]

**Comment by dOrgJelli** [comment]
@orishim could you make typeforms for these two?

**Comment by dOrgJelli** [comment]
@mrrobot16 is going to hop on implementing this.

**Comment by orishim** [comment]
Sure thing. Sounds good!

**Comment by orishim** [comment]
https://dorgtech.typeform.com/to/IaeXKv
