### ISSUE TITLE
Add 'download template' option for CSV file

### ISSUE THREAD

**Issue by orishim** [dOrgTech/DAOcreator#179]
On the Members view the user has the option to attach a CSV file.

Next to the 'Upload File' button there could be a 'Download Template' button that lets the user download a properly formatted CSV file with an example row filled in.

**Comment by dOrgJelli** [comment]
Love this, definitely agree!

**Comment by dOrgJelli** [comment]
@mrrobot16 or @cbrzn, interested in tackling this?

**Comment by mrrobot16** [comment]
Yeah sure we could tackle that!

**Comment by mrrobot16** [comment]
We can close this issue can we?

**Comment by dOrgJelli** [comment]
Yep!
