### ISSUE TITLE
Ready, Set, Deploy

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/DAOcreator#187]
Simplify the process into as few clicks as possible by:
- Having the user choose from a few DAO configuration options (ex: Grant DAO, Payroll DAO, Token Holder DAO, Hackathon DAO, etc)
- If members aren't predefined through a reputation allocation scheme, ask the user "want to add more members than just yourself?", and if they say yes they'll be given the "add members" screen.

With both of these, they should be able to (1) click a preset DAO config and (2) verify it's just them who's a member and (3) deploy.

**Comment by orishim** [comment]
This redesign is currently being wireframed by @stink3finger.

See initial spec [here](https://www.notion.so/dorg/DAOCreator-Beta-c9811132b5de437fbff678ae356020a5)

**Comment by orishim** [comment]
Related [161](https://github.com/dOrgTech/DAOcreator/issues/161)

**Comment by dOrgJelli** [comment]
Related https://github.com/dOrgTech/DAOcreator/issues/241

**Comment by dOrgJelli** [comment]
Closing this as the new design @pimato has created will create this type of experience.
