### ISSUE TITLE
Deployment Improvements

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/DAOcreator#200]
- Detect and error if user selects unsupported networks.
- Improve how no Metamask is handled.
- Improve how rejected Web3 access is handled.
- Remove the back button once deployment has started.
- Stop the user from closing the tab if deployment has started by giving them a warning message popup.
- Export { Log, Env, Result, DAOConfig }

**Comment by orishim** [comment]
Closing these related issues: [38](https://github.com/dOrgTech/DAOcreator/issues/38), [121](https://github.com/dOrgTech/DAOcreator/issues/121), [50](https://github.com/dOrgTech/DAOcreator/issues/50)

**Comment by nickplace** [comment]
> * Detect and error if user selects unsupported networks.

Which networks should be prevented from working with the app?

**Comment by dOrgJelli** [comment]
@nickplace any network that's not in DAOstack's migration.json file:
https://github.com/daostack/migration/blob/master/migration.json

We should check this after we fetch the network here:
https://github.com/dOrgTech/DAOcreator/blob/989f890bdc45fb66c543d7d97448dd77bb793342/src/lib/dependency/arc/migration.ts#L23

And report back to the user that they are using an unsupported network.
