### ISSUE TITLE
Stuck in Voting Configuration settings if Activation Time is set to earlier than Now.

### ISSUE THREAD

**Issue by orishim** [dOrgTech/DAOcreator#212]
If I set the activation time to within a couple hours of now, then I can't hit save or exit out of the dialog.

This is very confusing as there are no warnings anywhere. This behavior either shouldn't be there, or if there is a reason for not allowing an activation time within this period, that time should just not be selectable.

_
Edit: This issue occurs if time is set to a time earlier than now but still today.

**Comment by mrrobot16** [comment]
Weird, cause it lets me do it.

**Comment by orishim** [comment]
Ah I see the issue: It's only when you set an activation time earlier in the same day.

The dialogue should either not let you set a time earlier than now, or give a warning when you do.
