### ISSUE TITLE
preceding 0 in Voting Configuration Settings 

### ISSUE THREAD

**Issue by orishim** [dOrgTech/DAOcreator#213]
If you backspace/del the numbers in any of the fields in the first 4 rows (the time ones), then an annoying 0 remains. The only way to get rid of the 0 is by selecting it and then deleting.

**Comment by mrrobot16** [comment]
What do we want it to be shown if users deletes/backspace?

**Comment by orishim** [comment]
Right now if there is a '7' and I backspace, it turns into a '0'. Then if I type '7' it becomes '07'.

Backspacing should just result in no value being there. 

This just felt confusing to me but maybe it's not a real issue for most.

**Comment by mrrobot16** [comment]
Oh I see what you mean, great :) I will take a look at it today.

**Comment by mrrobot16** [comment]
@orishim checkout https://github.com/dOrgTech/DAOcreator/pull/226 its fixed now.
