### ISSUE TITLE
Able to add founder with 0 rep, 0 token (but fails on deployment)

### ISSUE THREAD

**Issue by orishim** [dOrgTech/DAOcreator#214]
Members screen lets you add a founder with Rep and Tokens set to 0. But the first deployment tx returns an error:
`Error: Returned values aren't valid, did it run Out of Gas?
`

We shouldn't allow founders with 0 Rep and 0 Token (Rep or Token should be non-zero). If user tries to add founder with 0 Rep AND 0 Token, they should get warning message: "Founder can't have 0 Rep and 0 Tokens"

**Comment by mrrobot16** [comment]
![Screen Shot 2019-10-17 at 4 06 04 PM](https://user-images.githubusercontent.com/761735/67043419-0ea8a600-f0f8-11e9-8e9f-25b181a3bf6a.png)

**Comment by mrrobot16** [comment]
Added a validation to those fields.

**Comment by orishim** [comment]
Nice! Thanks for getting on this so quickly.

Just to make sure, you can still put one of them to 0, correct?

**Comment by mrrobot16** [comment]
i guess i am confused. Can users input 0 for Rep and 0 Tokens?. What is it that we are trying to avoid from happening?

**Comment by mrrobot16** [comment]
Or question which can be zero? Can Rep be 0 as Token not? Here is where i think i am confused.

**Comment by orishim** [comment]
A founder can have zero Rep and non-zero tokens. A founder can have zero tokens and non-zero Rep. But a founder cannot have zero Rep and zero tokens.

**Comment by mrrobot16** [comment]
Ok cool. I will take a look at that. I am not sure if the validations are set to check those conditionals. But I will check it out later today.

**Comment by dOrgJelli** [comment]
After looking into this further @mrrobot16 @orishim it is actually possible to have a founder with 0 REP and 0 DAOToken, but the contract does require you to have at least one founder address in the array (not sure why).

The reason why you might want to do this is because you may have a DAO that's for token holders where they will redeem their REP at a later time, so the initial creation has 0 REP holders.

**Comment by dOrgJelli** [comment]
Requiring at least 1 founder: https://github.com/daostack/arc/blob/69f5e3328da192839ed4ccf517ae1bd57695edd8/contracts/universalSchemes/DaoCreator.sol#L183

Not requiring token or REP amounts to be > 0: https://github.com/daostack/arc/blob/69f5e3328da192839ed4ccf517ae1bd57695edd8/contracts/universalSchemes/DaoCreator.sol#L192

**Comment by dOrgJelli** [comment]
Closed with this PR: https://github.com/dOrgTech/DAOcreator/pull/231
