### ISSUE TITLE
Remove whitespace from CSV import (or at least throw error)

### ISSUE THREAD

**Issue by orishim** [dOrgTech/DAOcreator#215]
## Problem
If there are any spaces after address, Rep, or Token then the CSV then I am still able to continue to deploy step, but then I get this error when trying to deploy:

After pressing deploy, and continue but before I am prompted to confirm the first tx, I get this:
Extra 
`Error: invalid address (arg="_founders", coderType="address", value="0xf8d1d34956cea24718cf8687588d6fedbc6d9aa6\t")
`
because of the extra tab character after the address.

or 
`Error: invalid address (arg="_founders", coderType="address", value="0xce7298e5ef1ae8af0573edc2ebd03ab0f837e214 ")
`
because of the extra space after the address.

## Solution
Remove whitespace from CSV's when they are imported (better option) or at least give an error warning telling the user to do so (worse option)

**Comment by mrrobot16** [comment]
Checkout PR https://github.com/dOrgTech/DAOcreator/pull/217, I agree with 
> Remove whitespace from CSV's when they are imported (better option)
>
So i added that solution.
