### ISSUE TITLE
Stop user from accidentally exiting the while deploying

### ISSUE THREAD

**Issue by orishim** [dOrgTech/DAOcreator#219]
While the user is setting up their DAO, we don't care if they exit because we save the state and when they come back to the URL they'll be able to hit resume and pickup from where they were. We do however care about them accidentally exiting when they're deploying the DAO. If they accidentally close the page while deployment is in progress, we should show a popup saying "if you leave the page your deployment progress will be lost" or something to that affect. - Jordan

**Comment by dOrgJelli** [comment]
Completed in this PR (thanks @nickplace !): https://github.com/dOrgTech/DAOcreator/pull/238
