### ISSUE TITLE
Upgrade arcVersion dependency

### ISSUE THREAD

**Issue by orishim** [dOrgTech/DAOcreator#220]
- In the short term we just need to manually refactor from 0.0.1-rc.23 to 0.0.1-rc.30.

- In the longer term we'd want to support new versions automatically

- See discussion [here](https://github.com/daostack/subgraph/pull/362)

**Comment by mrrobot16** [comment]
@dOrgJelli I have checked the version inside of https://github.com/daostack/migration, it currently is "0.0.1-rc.32-v0". Shall we update it manually to that version, before working on an automated solution to keep track of changes inside of daostack/migration version?

**Comment by dOrgJelli** [comment]
Yes I'm actually working on this now @mrrobot16, will push shortly

**Comment by dOrgJelli** [comment]
This was completed in this PR: https://github.com/dOrgTech/DAOcreator/pull/235
