### ISSUE TITLE
TypeError: Cannot read property 'dao' of undefined

### ISSUE THREAD

**Issue by pimato** [dOrgTech/DAOcreator#229]
Hey guys,

I am currently trying to create a DAO on kovan and it seems like there is some issue with the interface:

<img width="953" alt="Screenshot 2019-11-11 at 11 47 27" src="https://user-images.githubusercontent.com/5337809/68581700-3ed63100-0479-11ea-8227-1212c0a7ea84.png">

Web3 provider: Metamask
Network: Kovan
Browser: Version 0.70.123 Chromium: 78.0.3904.97 (Official Build) (64-bit)
os: macOS Catalania 10.15.1 (19B88)

**Comment by dOrgJelli** [comment]
That's strange this happens to you, when I try Kovan it gives me the "proper" error for when I hit `yes` which basically says "we cannot find DAOstack contracts on this network":
![image](https://user-images.githubusercontent.com/5522128/68595044-09d9d680-0499-11ea-86f8-ead82b2ae4d9.png)

Do you see this same error if you switch to Rinkeby @pimato?

**Comment by pimato** [comment]
yes, also on Rinkeby:

<img width="953" alt="Screenshot 2019-11-11 at 16 06 30" src="https://user-images.githubusercontent.com/5337809/68597463-4ad3ea00-049d-11ea-912d-5cc4926d22c5.png">

<img width="636" alt="Screenshot 2019-11-11 at 16 06 37" src="https://user-images.githubusercontent.com/5337809/68597480-532c2500-049d-11ea-9418-b78d14560c35.png">

**Comment by orishim** [comment]
Why was this closed? Is there a link to a PR where this issue was addressed?

**Comment by dOrgJelli** [comment]
So the "problem" was that this error shows up when you click "no" to the question of "About to migrate new DAO. Continue?"

I've changed the code to properly detect when the user hits no, and we display an error accordingly letting them know to continue they must hit yes. This prompt comes from within the migration script, so it isn't 100% in our control when this was happening, which caused this originally to be an uncaught error.
