### ISSUE TITLE
UX bugs

### ISSUE THREAD

**Issue by nickplace** [dOrgTech/DAOcreator#237]
- [ ] Make it more clear that deployment is progressing. Migration confirm could be a dialog? Spinner for pending transactions? Loading bar?
- [ ] Info dialog on migration page offsets page layout (does it still w/ new layouting?)
- [x] Ignore saved states w/ no data
- [x] [Object Object] printed in log when Tx deployment fails
- [ ] Clear saved DAO configuration after successful migration.
- [ ] ~~Save references to recently deployed DAOs in localStorage?~~ (Moved Here: https://github.com/dOrgTech/DAOcreator/issues/240)
- [ ] ~~Move schemes to first step?~~ (Moved Here: https://github.com/dOrgTech/DAOcreator/issues/244)

**Comment by dOrgJelli** [comment]
@nickplace could you elaborate on "Info dialog on migration page..."?

**Comment by dOrgJelli** [comment]
Created this issue for "Save references to recently deployed DAOs": https://github.com/dOrgTech/DAOcreator/issues/240

**Comment by dOrgJelli** [comment]
@pimato do you have an opinion on "Move schemes to first step?"

**Comment by dOrgJelli** [comment]
@nickplace a spinner already exists when you're deploying, do you think that's enough?

**Comment by dOrgJelli** [comment]
> @pimato do you have an opinion on "Move schemes to first step?"
It looks like we do want to do this judging by the Beta spec [here](https://www.notion.so/dorg/DAOCreator-Beta-c9811132b5de437fbff678ae356020a5). I'll make another task that's dependent on DAO templates for moving this to the front of the stepper.

**Comment by nickplace** [comment]
> @nickplace a spinner already exists when you're deploying, do you think that's enough?

That screen could be more clear, IMO. I honestly missed the "Do you want to deploy?" Dialog inside of the Log at first. Saw that the spinner was spinning, assumed no input was needed.

**Comment by dOrgJelli** [comment]
Closing as we've finished UI V2 which should address all of these issues.
