### ISSUE TITLE
DAO Templates

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/DAOcreator#241]
Have the user choose from a few DAO configuration options (ex: Open Community, Membership Club, Worker Co-op, Token Holder)

**Comment by dOrgJelli** [comment]
This requires a design / specification, @orishim @pimato have any thoughts?

**Comment by orishim** [comment]
I don't think this would be useful anymore with the new simplified design.

**Comment by dOrgJelli** [comment]
Okay, going to close for now
