### ISSUE TITLE
Cotary Create Implementation

### ISSUE THREAD

**Issue by mrrobot16** [dOrgTech/DAOcreator#246]
This issue is for PR #263

**Comment by dOrgJelli** [comment]
@mrrobot16 and I are coordinating around this, ensuring we're able to make progress here while waiting for (1) landing page & DAOcreator to be separated and (2) DAOcreator turned into a monorepo with DAOcreatorUI and DAOcreatorLib.

**Comment by mrrobot16** [comment]
Sup people, we gonna start this week these following issues: 
https://github.com/dOrgTech/DAOcreator/issues/260
https://github.com/dOrgTech/DAOcreator/issues/261
https://github.com/dOrgTech/DAOcreator/issues/262
