### ISSUE TITLE
Interactive Wireframe

### ISSUE THREAD

**Issue by orishim** [dOrgTech/DAOcreator#252]
https://www.figma.com/proto/t77rlBAupEeqIYHFBBpqrl/Playground?node-id=723%3A28&viewport=48%2C337%2C0.14125387370586395&scaling=min-zoom

Mostly done, just a few finishing touches.

**Comment by pimato** [comment]
What needs to be done:

- https://github.com/dOrgTech/DAOcreator/issues/254
