### ISSUE TITLE
Add Dropdown design reference for main widget menu (Export, Import)

### ISSUE THREAD

**Issue by pimato** [dOrgTech/DAOcreator#256]
The main `Create Organisation - Widget` has a menu on the top right corner which still needs design reference for the dropdown menu where users can always export/import the state of the current configuration process.

**Comment by pimato** [comment]
[Playground](https://www.figma.com/proto/t77rlBAupEeqIYHFBBpqrl/Playground?node-id=1265%3A8854&viewport=424%2C571%2C0.33626240491867065&scaling=min-zoom)

[Design specification](https://www.figma.com/file/t77rlBAupEeqIYHFBBpqrl/Playground?node-id=1265%3A8854)

**Comment by pimato** [comment]
@mrrobot16 just so you are aware of this design specification.

**Comment by mrrobot16** [comment]
@pimato great thanks :)
