### ISSUE TITLE
Cotary Create: translation of simple options into scheme voting machine configuration

### ISSUE THREAD

**Issue by mrrobot16** [dOrgTech/DAOcreator#269]

**Comment by mrrobot16** [comment]
![Screen Shot 2019-12-16 at 5 01 38 PM](https://user-images.githubusercontent.com/761735/70946745-c2111680-2025-11ea-9b71-08d2ef0b996f.png)
We need to find a way to grab those simple options into a VotingMachine config objects. This translation should be done inside "@dorgtech/daocreator-lib" codebase for module is inside of "packages/lib".

**Comment by dOrgJelli** [comment]
Hey @Flash-Git @mrrobot16, some thoughts on how this might be implemented:
- I think this should be implemented at the UI layer, and the forms in the Lib should stay unopinionated with how things are abstracted to be made more user friendly.
- In the UI, when one of the toggles is switched, the DAOForm (or nested forms) will be modified to reflect the changes the user is interested in.

Also a quick note that "Reward Correct Voters" and "Penalize Incorrect Voters" cannot be treated separately (cc @orishim @pimato), as they both change the same parameter named "votersReputationLossRatio". The REP lost goes to the voters who were correct, so it simultaneously rewards and penalizes.

The below code describes how this should be implemented. I was going to describe it at a high level but it lead to too much text... code is much easier to read and understand in this case.

```typescript
/// module level type defs and global static var "schemeSpeeds"
enum DAOSpeed {
  Slow,
  Medium,
  Fast
}

class SchemePresets extends Map<SchemeType, GenesisProtocolPreset> { }
class SchemeSpeeds extends Map<DAOSpeed, SchemePresets> { }

const schemeSpeeds: SchemeSpeeds = new SchemeSpeeds([
  [DAOSpeed.Slow, new SchemePresets([
    [SchemeType.ContributionReward, GenesisProtocolPreset.Critical],
    [SchemeType.SchemeRegistrar, GenesisProtocolPreset.Critical],
    [SchemeType.GenericScheme, GenesisProtocolPreset.Critical]
  ])],
  [DAOSpeed.Medium, new SchemePresets([
    [SchemeType.ContributionReward, GenesisProtocolPreset.Normal],
    [SchemeType.SchemeRegistrar, GenesisProtocolPreset.Critical],
    [SchemeType.GenericScheme, GenesisProtocolPreset.Normal]
  ])],
  [DAOSpeed.Fast, new SchemePresets([
    [SchemeType.ContributionReward, GenesisProtocolPreset.Easy],
    [SchemeType.SchemeRegistrar, GenesisProtocolPreset.Normal],
    [SchemeType.GenericScheme, GenesisProtocolPreset.Easy]
  ])]
])

/// inside a function somewhere
// you should already have these values available to you
const dao = new DAOForm()
const speed = DAOSpeed.Fast
// these are our toggle values
const rewardSuccessfulProposer = false
const rewardAndPenalizeVoters = false
const penalizeIncorrectVoters = false
const autoBetAgainstProposals = false

daoForm.$.schemes.$.forEach(scheme => {
  const preset = schemeSpeeds[speed][scheme.type];
  if (preset === undefined) {
    throw Error("Unimplemented Scheme Speed Configuration");
  }

  const votingMachine = scheme.$.votingMachine

  // Initialize the scheme's voting machine to the Genesis Protocol Preset
  votingMachine.preset = preset;

  // Apply the effects of the toggles
  if (!rewardSuccessfulProposer) {
    votingMachine.$.proposingRepReward.value = "0";
  }
  if (!rewardCorrectVoters) {
    votingMachine.$.votersReputationLossRatio.value = "0";
  }
  if (!autoBetAgainstProposals) {
    votingMachine.$.minimumDaoBounty.value = "0"
  }
});
```
Let me know if this above code snippet doesn't make sense.

Lastly, I'm unsure what should change when the user toggles "Distribute DAO_NAME Token", @pimato @orishim were you around when this was talked about and added to the sped?

**Comment by orishim** [comment]
Ahh good catch, I had thought these were two different parameters. I think instead of 2 checkboxes, it should just be one that says:

- [x] Reward correct voters and penalize incorrect voters

**Comment by Flash-Git** [comment]
Thanks @dOrgJelli! I'm happy to implement it at the UI layer.

**Comment by mrrobot16** [comment]
@Flash-Git Great job mate!

**Comment by orishim** [comment]
Just realized I didn't answer your second question @dOrgJelli .

When "Distribute DAO_NAME Token" is not checked, the token column and distribution bar should disappear in the Members step. 
@cbrzn @mrrobot16
