### ISSUE TITLE
Cotary Create: Good Looking UI

### ISSUE THREAD

**Issue by mrrobot16** [dOrgTech/DAOcreator#274]
For this issue we are gonna styling/comply as much as possible with Cotary Create ui specs found in [figma](https://www.figma.com/proto/t77rlBAupEeqIYHFBBpqrl/Playground)

TODO Stylings

- Modal Advance Form Component
- Accordion Component

**Comment by cbrzn** [comment]
<img width="247" alt="Screenshot 2019-12-28 at 18 04 10" src="https://user-images.githubusercontent.com/21031138/71550420-b9adc980-299d-11ea-8763-6327983d6caa.png">

The votationMachine params that we iterate through in the form field are these. The new mock ups does not include daoBountyConst variable - Should we skip it in the the iteration of our UI? Or the mock up is missing a field?

This is the mock up:
![paste](https://user-images.githubusercontent.com/21031138/71550423-ccc09980-299d-11ea-964e-786e942067bd.png)

**Comment by orishim** [comment]
Yeah I think the mock up is just missing the field. It should be in there

**Comment by cbrzn** [comment]
![image](https://user-images.githubusercontent.com/21031138/71563579-eaeece00-2a5f-11ea-8039-11eb8cfff5af.png)

On step two, if the scheme configuration is done through the advanced mode, what should we show? @orishim @dOrgJelli

**Comment by dOrgJelli** [comment]
@cbrzn Not sure, I would say just put the name of each enabled scheme with a checkmark. We can include some information similar to this if we think it makes sense (@pimato thoughts?):
![image](https://user-images.githubusercontent.com/5522128/71566979-77f64f00-2a81-11ea-9513-9d0769bbcb27.png)

**Comment by orishim** [comment]
Yea the logic for these was never specified anywhere. But I do NOT think we should add anything new in this view (the whole point is to keep this view hyper simple but advanced users can tweak individual parameters in the advanced view).

- If any of the three `*periodLimit` parameters are changed from the default set by Fast/Medium/Slow, then these options should be greyed out
- if `proposingRepReward > 0`, display "Reward successful proposer" with checkmark
- If `votersReputationLossRatio > 0`, display "Reward correct voters and penalize incorrect voters" with checkmark (see [here](https://github.com/dOrgTech/DAOcreator/issues/269#issuecomment-567338607) on why these items are combines
- if `minimumDAOBounty > 0` , display "Auto-bet against every..." with a checkmark

The "Distribute DAO_TOKEN" is not affected by any edits made in the advanced mode. I personally think it's confusing to have this option in step 2 and think it should be decided by the user in step 3, but that would require some additional input by @pimato.
