### ISSUE TITLE
Cotary Create: Advance Configuration Form

### ISSUE THREAD

**Issue by mrrobot16** [dOrgTech/DAOcreator#275]
When users clicks save configuration it should then modify DAOForm.schemes object. 
When users has save/modify the form in Advance mode should it disable simple options? How should we play this out from a ui standpoint @dOrgJelli @orishim

**Comment by Flash-Git** [comment]
This doesn't answer the issue but it might be worth pointing out that currently the DAOForm.schemes object is updated through hooks whenever a simple option is changed. I don't believe that `Set Configuration` does more than move the user to the next step.

**Comment by dOrgJelli** [comment]
Yah modifying DAOform.schemes happens whenever a change in the UI is made, and not just when the user clicks “next step”.

To answer your question @mrrobot16, I think we should disable the “simple mode” toggles if the user decides to modify the options manually. Maybe we just have them toggle an “advanced” toggle which changes the UI from the toggles to the scheme editor Corkus has designed.

**Comment by mrrobot16** [comment]
AdvanceForm to SimpleForm logic.

- If any of the three `*periodLimit` parameters are changed from the default set by Fast/Medium/Slow, then these options should be greyed out
- if `proposingRepReward > 0`, display "Reward successful proposer" with checkmark
- If `votersReputationLossRatio > 0`, display "Reward correct voters and penalize incorrect voters" with checkmark (see [here](https://github.com/dOrgTech/DAOcreator/issues/269#issuecomment-567338607) on why these items are combines
- if `minimumDAOBounty > 0` , display "Auto-bet against every..." with a checkmark
