### ISSUE TITLE
Cotary Create: Advance Form input NaN bug.

### ISSUE THREAD

**Issue by mrrobot16** [dOrgTech/DAOcreator#281]
Whenever users inputs numbers it automatically sets the input field to NaN. Weird we will look into it.

![Screen Shot 2020-01-04 at 2 15 22 AM](https://user-images.githubusercontent.com/761735/71770376-d5632380-2ef9-11ea-87b4-f85e6bbcd99c.png)

**Comment by cbrzn** [comment]
This has been fixed in PR #278
