### ISSUE TITLE
Cotary Create: Feedback January 16

### ISSUE THREAD

**Issue by mrrobot16** [dOrgTech/DAOcreator#297]
1. TOKENS Move "distribute token" check item to the top of the Add Members section. If unchecked, hide tokens column and set to 0 for each member. Leave unchecked by default. 
2. REPUTATION Every new member should get 100 rep by default, which can be edited with a button on the side. This way the user only has to enter addresses. 
3. Clicking anywhere we have an eth address should copy the full address to clipboard

**Comment by Flash-Git** [comment]
1. Has been handled under #319.
2. Every user now gets 100 rep by default but no button has been added to change the default value as of yet.
3. I kept the open to etherscan functionality with an extra icon button and clicking on an address now copies it to clipboard.

**Comment by mrrobot16** [comment]
@orishim "REPUTATION Every new member should get 100 rep by default, which can be edited with a button on the side." are you reffering to adding a new button that edites the default value ? Or you are talking about the existing button? Whats the most simple way?

**Comment by orishim** [comment]
Existing button could work, or just clicking on the number to edit it. Not remembering what we have their currently as I can't run locally.

**Comment by mrrobot16** [comment]
@orishim currently you can edit a member row tokens and rep after a member address is added.
