### ISSUE TITLE
Create a DAO

### ISSUE THREAD

**Issue by sogasg** [dOrgTech/DAOcreator#3]
Make it possible for anybody to create a basic DAO.

The DAO can be created through a wizard that includes the following:
1. Set name, token name
2. Set the founders
3. Setup your controller (schemas, constraints, voting machine)
4. Launch the DAO

This issue is part of Scenario: [1 DAO Setup and Configuration](https://github.com/dOrgTech/dOrg-doc/blob/master/scenario-specs/1-setup-and-configure.md)

Work branch: [feature/create-dao](https://github.com/dOrgTech/dOrg-dApp/tree/feature/create-dao)

**Comment by sogasg** [comment]
Maybe something like this.
Basically the idea is a starting with a very straightforward wizard, then we keep changing it as we see fit.

_The bottom four squares are different screens._

![img_1872](https://user-images.githubusercontent.com/2156509/47743798-276a4280-dc80-11e8-9fb3-8677d52c1933.JPG)
Please give me some feedback.

**Comment by JordanEllis6809** [comment]
Awesome drawing, I'll add my own soon when inspiration sparks next! I have a few notebook drawings but nothing as detailed as this, I'll try and build mine off of this and see if we can get a bit further in the envisioning.

**Comment by cd10012** [comment]
Should the schema, constraints, and voting machine still be configurable when a user selects a template? Or should that option only be allowed for custom templates? 

Maybe we would benefit from a UX perspective to breakout the DAO feature wizard into two pages:

1. A list view of preconfigured templates and their scenarios. There would maybe some block text for each template to explain the motivations and use cases behind each. And later down the line we show DAO's using that template for examples.

2. Completely custom wizard where you can assign contract addresses for those three components/contract interfaces.

I think the main benefit of this is that it will hide some of the complexity for non-technical people, while still retaining the possibility to add more dev tools to this part of the kit w/o clutter. As per our discussion mocks coming soon!

**Comment by sogasg** [comment]
I think it sounds like a good idea to divide it like that. It should be easy to use for non-technical users.

However, I think it should be possible to edit the schemas and constraints that are included in the templates. But I dont think this should be part of the normal flow, just a small "edit schemas/constraints/voting" button or something. But this can be included later.

**Comment by cd10012** [comment]
Not much of a designer here 😅
But it'll give us something to iterate on. Sent over an invite to comment.

<img width="1001" alt="screen shot 2018-11-10 at 6 50 03 pm" src="https://user-images.githubusercontent.com/7246942/48307398-e0027280-e519-11e8-8256-b500376d67b8.png">

<img width="996" alt="screen shot 2018-11-10 at 6 50 21 pm" src="https://user-images.githubusercontent.com/7246942/48307399-e4c72680-e519-11e8-8eb9-eaf47220d352.png">

<img width="998" alt="screen shot 2018-11-10 at 6 50 31 pm" src="https://user-images.githubusercontent.com/7246942/48307402-e7c21700-e519-11e8-8d23-8591ffb1c67d.png">

When clicking "Create" under templates:
<img width="1003" alt="screen shot 2018-11-10 at 6 54 07 pm" src="https://user-images.githubusercontent.com/7246942/48307407-07593f80-e51a-11e8-8f63-c779d7964f7e.png">

Last page after clicking "Next"
<img width="992" alt="screen shot 2018-11-10 at 6 50 41 pm" src="https://user-images.githubusercontent.com/7246942/48307417-4091af80-e51a-11e8-891d-afebabeba988.png">
 on DAO Templates view:

**Comment by JordanEllis6809** [comment]
I started creating a mock of this drawing in photoshop, but realized there are still too many unknowns. Long story short, I think it'd be cool if this "wizard" could evolve from text boxes into an interactive & geometrically backed configuration UI. Having the visual representation of the system you're creating 
could resolve a lot of confusion and help people get a bit more creative with what they're creating and planing on using.

![img_29921](https://user-images.githubusercontent.com/5522128/48319322-5e661f80-e5c1-11e8-8c0a-21daa8a9d43d.jpg)
