### ISSUE TITLE
DAO Explorer

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/DAOcreator#30]
Make it possible for users to explore the DAO universe.

At a high level, the DAO Explorer should be able to support/show:
1. Geometric DAO Representations
2. DAO Relationships
3. DAO Members
4. DAO Activity
5. Member Activity
6. Searching
7. Inspecting

More in-depth design work will be conducted once the first prototype is created.

This issue is part of Scenario: [6 DAOs Are Discoverable](https://github.com/dOrgTech/vision/blob/master/scenario-specs/6-daos-are-discoverable.md)

**Comment by orishim** [comment]
This seems out of scope for the 'DAO creator'

**Comment by dOrgJelli** [comment]
Agreed, closing for now.
