### ISSUE TITLE
Cotary Create: On step 4 "Install Organization", the text above the "install" button doesn't really make sense. 

### ISSUE THREAD

**Issue by mrrobot16** [dOrgTech/DAOcreator#305]
On step 4 "Install Organization", the text above the "install" button doesn't really make sense. Are these supposed to be the two different steps?

**Comment by mrrobot16** [comment]
@dOrgJelli Shall we just render "Deploy DAO"?

**Comment by mrrobot16** [comment]
When you say the text you meant this text ?

![Screen Shot 2020-01-23 at 6 25 48 PM](https://user-images.githubusercontent.com/761735/73032704-d1963300-3e0d-11ea-844f-304fdada9ac3.png)

**Comment by Flash-Git** [comment]
I believe he means everything in the screenshot that isn't the part you highlighted there @mrrobot16. We should add actual icons and change the styling to match the mock-up.

**Comment by mrrobot16** [comment]
@Flash-Git oh i see i missed this comment, feel free to tackle it

**Comment by Flash-Git** [comment]
I talked to @cbrzn and this is a better fit for him atm!
