### ISSUE TITLE
Add Unity WebGL Project Support

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/DAOcreator#31]
For the DAO Explorer, we've decided it'd be most effective to build it within a Game Engine so that we don't have to rewrite low level systems (graphics, object culling, physics, etc). We think Unity's WebGL support might work best for us, so the first step is to integrate it with our react project using this package: [react-unity-webgl](https://www.npmjs.com/package/react-unity-webgl)

Work being done in this branch: [unity-webgl-integration](https://github.com/dOrgTech/dOrg/tree/unity-webgl-integration)

**Comment by orishim** [comment]
This seems out of scope for the DAO creator.

**Comment by dOrgJelli** [comment]
Agreed @orishim, this was back when the app was an overarching "do it all" app, and I really wanted to (still do) create a 3D visualization for the DAO ecosystem.
