### ISSUE TITLE
Cotary Create: Copy Changes, Tooltips 

### ISSUE THREAD

**Issue by orishim** [dOrgTech/DAOcreator#344]
PR for UI part of this issue: https://github.com/dOrgTech/DAOcreator/pull/350

PR for Lib part of this: ?

### `NAMING CHANGES` + TOOLTIPS

- [x] `Name` + Your organization’s name (cannot be changed after launch)  -> **This is Lib change**

- [x] `Symbol` + Abbreviation to identify your organization’s token (cannot be changed after launch) -> **This is Lib change**

- [x] `Decision-making speed` + How quickly your organization processes proposals

- [x] [Add tooltips to Slow/Medium/Fast:] **TODO in UI**
  - `Slow` + Funding & Voting Power: 4-30 days, Plugins: 8 - 60 days  
  - `Medium` + Funding & Voting Power: 1-7 days, Plugins: 4-30 days
  - `Fast` + Funding & Voting Power: 1-7 days, Plugins: 1-7 days

- [x] `Reward successful proposers` + Successful proposers gain additional voting power

- [x] `Reward correct voters and penalize incorrect voters` + Voters on the winning side of proposals gain voting power, voters on the losing side lose voting power

- [x] `Auto-incentivize proposal curation` + The organization bets against every proposal to incentivize the GEN curation network

- [x] `Distribute X token` + Distribute your organization’s native token at launch (regardless of initial distribution, the organization will be able to create more tokens after launch through proposals)

### OTHER NOTES
- [x] Change Symbol warning to: “must be all caps and 4 characters or less” -> **This is Lib change**
- [x] “Configure Schemes” -> “Configure”
- [x] “Recommend Configuration” -> “Recommended Configuration”
- [x] Change subtitle to “Your organization uses a reputation-weighted voting system to make decisions.”
- [x] “Advanced Configuration” -> “Advanced”
- [x] “Contribution Reward” -> “Funding and Voting Power” -> **This is Lib change**
- [x] “Scheme Registrar” -> “Plugins Manager” -> **This is Lib change**
- [x] “Install Organization” -> “Launch”

@mrrobot16

**Comment by Flash-Git** [comment]
Going to start on this

**Comment by Flash-Git** [comment]
Are we changing the lib or just the UI?

**Comment by mrrobot16** [comment]
@Flash-Git we have to change the lib for the warning message only. 

Other than its UI i believe.

**Comment by mrrobot16** [comment]
@dOrgJelli how shall we play this out for the changes needed to be made of the Lib side rather than UI.

**Comment by mrrobot16** [comment]
PR for UI part of this issue: https://github.com/dOrgTech/DAOcreator/pull/350

PR for Lib part of this: ?

**Comment by mrrobot16** [comment]
@Flash-Git Feel free to add tooltip for [Slow/Medium/Fast] Buttons

**Comment by orishim** [comment]
Instead of adding the warning symbol into the U.I., we could just change the copy like so:

- `Name` + Your organization’s name (cannot be changed after launch)

- `Symbol` + Abbreviation to identify your organization’s token (cannot be changed after launch)

**Comment by mrrobot16** [comment]
> Instead of adding the warning symbol into the U.I., we could just change the copy like so:
> 
> * `Name` + Your organization’s name (cannot be changed after launch)
> * `Symbol` + Abbreviation to identify your organization’s token (cannot be changed after launch)
> 
> I think that's better to keep the U.I. cleaner.. I've edited the post above to reflect this.

Cool will do that, thats how its designed we will change the copy in the library.

**Comment by orishim** [comment]
On second thought I think "Recommended Configuration" can be taken out entirely. The first line of that section can just be "Your organization uses.."

**Comment by dOrgJelli** [comment]
> @dOrgJelli how shall we play this out for the changes needed to be made of the Lib side rather than UI.

I'm not sure what changes are needed within the Lib. If it's just copy, you can simply make those changes, PR them, and I can make a new release once it's reviewed.

**Comment by mrrobot16** [comment]
Ok cool will do.

**Comment by orishim** [comment]
Still not done:
- DAO Name -> Name
- DAO Symbol -> Symbol
- Auto-bet against every proposal to incentivise curation -> Auto-incentivize proposal curation
