### ISSUE TITLE
Cotary Create: When the user exits the app during deployment

### ISSUE THREAD

**Issue by mrrobot16** [dOrgTech/DAOcreator#366]
When the user exits the app during deployment, they should be given a popup warning letting them know that all progress will be lost.

**Comment by Flash-Git** [comment]
There is already a popup that appears and warns the user when they attempt to leave during deployment. Unfortunately it's not customizable on newer browsers.
Although it's obviously not recommended, all progress isn't necessarily lost when exiting during deployment. In step 4, if the app finds a deployment in progress, it resumes from the last successful tx.

Will double check that this functionality is still in place before closing.

**Comment by Flash-Git** [comment]
Just checked and I did get the expected functionality here.
