### ISSUE TITLE
Cotary Create: add a DAOstack logo somewhere in the U.I.

### ISSUE THREAD

**Issue by mrrobot16** [dOrgTech/DAOcreator#371]
Add a DAOstack logo somewhere in the U.I., the user should know that they are using DAOstack

**Comment by mrrobot16** [comment]
@orishim @pimato Where shall this go in place any ideas? We don't want to assume this either. So let us know what are you thoughts or if its up to us?

**Comment by mrrobot16** [comment]
@orishim @pimato

**Comment by orishim** [comment]
Maybe at the very bottom in the center it can just say something like "Powered by DAOstack"

**Comment by mrrobot16** [comment]
great thanks @orishim

**Comment by Flash-Git** [comment]
It's in the footer on alchemy for example.
![image](https://user-images.githubusercontent.com/20420828/74772509-6f0b4800-5290-11ea-9128-238bc13a59f5.png)
