### ISSUE TITLE
Cotary Create: Step 2 - Advanced View

### ISSUE THREAD

**Issue by mrrobot16** [dOrgTech/DAOcreator#372]
Feedback: #352 

- [x] Align Advanced View
- [x] Add Proposing Rep Reward to Advanced View
- [x] Set toggle defaults to True
- [x] Fix Advanced configuration values not persisting to deployment. 
- [x] Use the following values:

| SPEED | Queued (Funding & Voting Power) | Pre-Boosted (Funding & Voting Power) | Boosted (Funding & Voting Power) | Quiet Ending (Funding & Voting Power) | Queued (Plugin Manager) | Pre-Boosted (Plugin Manager) | Boosted (Plugin Manager) | Quiet Ending (Plugin Manager) |
|-|-|-|-|-|-|-|-|-|
| Slow | 30 days | 1 day 12 hrs | 3 days | 2 days | 60 days | 3 days | 6 days | 4 days |
| Medium | 7 days | 12 hrs | 1 day | 16 hrs | 30 days | 1 day 12 hrs | 3 days | 2 days |
| Fast | 7 days | 12 hrs | 1 day | 16 hrs | 7 days | 12 hrs | 1 day | 16 hrs |

If `Reward successful proposers` is off, set `Proposing Rep Reward` to 0
If `Reward correct voters and penalize incorrect voters` is off, set `Voter Reputation Loss` to 0
If `Auto-incentivize proposal curation` is off, set `Minimum DAO Bounty` & `DAO Bounty Const` to 0

**Comment by Flash-Git** [comment]
Feedback: #352
- [ ] "If the user disables the Scheme Registrar, we should have a warning letting them know that their DAO will not be able to modify and upgrade itself in the future. This warning should be in the Advanced Configuration view, and also in the final deployment view as this is a major thing users should be aware of."
- [ ] Contribution Reward and Scheme Registrar should not be disabled by default
