### ISSUE TITLE
Cotary Create: Blockies look wrong

### ISSUE THREAD

**Issue by Flash-Git** [dOrgTech/DAOcreator#384]
A lot of apps have the blockies icons but ours do not currently match them.

**Comment by mrrobot16** [comment]
@Flash-Git Mind sharing more about this issue? What you mean with ours does not currently match them ?

**Comment by Flash-Git** [comment]
Yep! This is my blockie identicon: 
![image](https://user-images.githubusercontent.com/20420828/74273898-7a4ef880-4d11-11ea-8fc8-816c2ac2d52b.png)

On the app, it shows as this:
![image](https://user-images.githubusercontent.com/20420828/74273965-96529a00-4d11-11ea-86c3-103302b524b1.png)

I'm looking into it now.

**Comment by Flash-Git** [comment]
We are using it correctly and the problem is consistent across v1 and v2 so I am switching libraries to https://github.com/MyCryptoHQ/ethereum-blockies-base64.

**Comment by Flash-Git** [comment]
If v1 is still being used it might be worth updating for that as well? @dOrgJelli
