### ISSUE TITLE
Lib: old version of web3 and thus web3-providers-ws breaks NPM install on Windows

### ISSUE THREAD

**Issue by dkent600** [dOrgTech/DAOcreator#389]
This library is using an old version of web3 (1.2.0) and thus an old version of web3-providers-ws which breaks `NPM install` on Windows.  Upgrading web3 (like to 1.2.4) would fix this problem

**Comment by mrrobot16** [comment]
@dkent600 thanks for the feedback, are you having this issue to run version 1 correct?

**Comment by dkent600** [comment]
@mrrobot16 Yes, I'm having the issue as I use a Windows computer and often use powershell.

**Comment by Flash-Git** [comment]
@dOrgJelli Have we tested it on windows?

**Comment by dOrgJelli** [comment]
We should move to Ethers.js as it's a much smaller bundle and doesn't have the same build issues Web3.js is known to have.

**Comment by dOrgJelli** [comment]
Going back on the thought of using ethers within the DAOcreator. This is useless at the moment, as the DAOcreator is only being used within Alchemy, which uses Web3 anyway. If we used ethers, it'd increase the size of Alchemy's bundle, not decrease it.

I've fixed the issue Doug was talking about in this PR: https://github.com/dOrgTech/DAOcreator/pull/478
