### ISSUE TITLE
can't npm install because appears to be git repo

### ISSUE THREAD

**Issue by dkent600** [dOrgTech/DAOcreator#394]
> node_modules/@dorgtech/daocreator-lib/node_modules/websocket: Appears to be a git repo or submodule.

**Comment by dkent600** [comment]
probably because of old version of web3

**Comment by dOrgJelli** [comment]
Hey @dkent600, this repo is a monorepo that uses yarn, so it means that you should (from root directory):
- Make sure you're using the right node version `nvm install $(cat .nvmrc)` `nvm use $(cat .nvmrc)`
- Install all packages by running `yarn`

Then you should be able to go into each directory and run commands there like `yarn build`.

Please feel free to DM me on Telegram if you're making changes to the daocreator-lib package. Something we need to do a better job of is adding contribution documentation to this repo :p sorry for the confusion

**Comment by dkent600** [comment]
> then you should be able to go into each directory and run commands there like yarn build.

That is just not an option.  I'm not working in your repo.  We include this package in Alchemy and are trying to NPM install Alchemy when experience this problem.

**Comment by dOrgJelli** [comment]
Oh very interesting, can you please provide me with steps to repro this locally so I can better understand what's going on @dkent600 ?

**Comment by dOrgJelli** [comment]
Also please feel free to DM me on Telegram for faster response times :P sorry about that

@dOrgJelli
