### ISSUE TITLE
Cotary Create: Schemes Preview

### ISSUE THREAD

**Issue by Flash-Git** [dOrgTech/DAOcreator#400]
The code for the preview showing the overview of the schemes config is needlessly complicated and doesn't appear to be entirely functional.

**Comment by dOrgJelli** [comment]
@Flash-Git can you include links to said code?

**Comment by Flash-Git** [comment]
@dOrgJelli Sure!

Mainly [this file](https://github.com/dOrgTech/DAOcreator/blob/dev/packages/ui_v2/src/components/utils/schemesUtils.ts).

**Comment by Flash-Git** [comment]
Reopening to redo changes for #401
