### ISSUE TITLE
Cotary Create: Styling feedback

### ISSUE THREAD

**Issue by pimato** [dOrgTech/DAOcreator#408]
Hey guys, 

I am gonna to request a change per comment in this issue

**Comment by pimato** [comment]
Border of the header:

currently looks like:
<img width="786" alt="Screenshot 2020-02-20 at 14 11 33" src="https://user-images.githubusercontent.com/5337809/74936788-14d2ca00-53eb-11ea-9171-eab23b0bcb26.png">

- remove margin
- color should be #EAEDF3 
- should not be aligned to the left and right side of the widget.

should look like:
<img width="833" alt="Screenshot 2020-02-20 at 14 11 46" src="https://user-images.githubusercontent.com/5337809/74936901-52cfee00-53eb-11ea-8286-6f99e50fa163.png">

**Comment by pimato** [comment]
Header Title to big

currently:
<img width="1128" alt="Screenshot 2020-02-20 at 14 21 35" src="https://user-images.githubusercontent.com/5337809/74937439-54e67c80-53ec-11ea-8cff-915a8ae5b5e5.png">

- letter-spacing: 0.6px;
- font-size: 18px instead of 28px
- title should be aligned vertical centered

should look like:
<img width="1103" alt="Screenshot 2020-02-20 at 14 23 06" src="https://user-images.githubusercontent.com/5337809/74937527-88290b80-53ec-11ea-80a6-7fc26108868e.png">

**Comment by pimato** [comment]
**Menu Button:**

Currenty:
<img width="375" alt="Screenshot 2020-02-20 at 14 34 26" src="https://user-images.githubusercontent.com/5337809/74938354-24074700-53ee-11ea-80c8-228af634eeb1.png">

Should:
- 32px width and height and not 35px
- 3 dots should have the color #536DFE 
- Button is not aligned centered
- Border color should be #EEF0FF 

Should look like:
<img width="357" alt="Screenshot 2020-02-20 at 14 37 41" src="https://user-images.githubusercontent.com/5337809/74938582-92e4a000-53ee-11ea-9bcf-d97b9e1b044e.png">

**Comment by Flash-Git** [comment]
Looks good!
You guys got this? @cbrzn @mrrobot16

**Comment by pimato** [comment]
**Navigation Indicator:**

Currently:
<img width="495" alt="Screenshot 2020-02-20 at 15 40 33" src="https://user-images.githubusercontent.com/5337809/74945159-87e23d80-53f7-11ea-9d2a-ac1b5a3790bf.png">

- margin left is currently 24px but should be 30px
- Set Description should have margin left of 20px to the number circle instead of 8px
- The size of the number circle should be 32px and not 28px
- The circles should be connected without any gaps
- The number in the circle is not aligned centered vertically and horizontally
- border color should be #EDEDEF
- active blue color should be: #1665D8 
- Set Description should have the color #1665D8

Should look like:
<img width="489" alt="Screenshot 2020-02-20 at 16 18 47" src="https://user-images.githubusercontent.com/5337809/74948494-af87d480-53fc-11ea-9af9-afd90064b360.png">

**Comment by mrrobot16** [comment]
@pimato Thanks for this. What else do you think we should tackle?

**Comment by pimato** [comment]
**Set Description Box**

Current:
<img width="805" alt="Bildschirmfoto 2020-02-25 um 12 38 36" src="https://user-images.githubusercontent.com/5337809/75244267-c9923000-57cb-11ea-8f7d-58972810edde.png">

changes:
- Content of the Set Description should have 30px padding-left & right and 24 px padding-top & bottom
- DAO Name should be renamed as in my mockups to Organisation Name
- Organisation name and Organisation Symbol should have a font-size of 12px and text color #9EA0A5 
- Placeholders should be there according my designs: "Organisation Name..." and "ABCT..."
- Placeholder text color should have the color #9EA0A5 
- Button disabled should have 
width: 134px; 
height: 34px;
border: 1px solid #EAEDF3;
border-radius: 3px;
font-size should be 14px
text-color: #78797B
