### ISSUE TITLE
Cotary Create:  Advanced form validation

### ISSUE THREAD

**Issue by Flash-Git** [dOrgTech/DAOcreator#415]
The advanced editor should enforce:
- [x] `boostedVotePeriodLimit` >= `quietEndingPeriod`
- [x] `minimumDaoBounty > 0`

**Comment by mrrobot16** [comment]
@dOrgJelli question, this should be done thru the lib instead of UI?

**Comment by dOrgJelli** [comment]
Yes it should be done in the lib

**Comment by dOrgJelli** [comment]
Let me know if you'd like me to do this, would be very quick

**Comment by Flash-Git** [comment]
@dOrgJelli Yes please!

**Comment by dOrgJelli** [comment]
Okay doing this now :P
