### ISSUE TITLE
Cotary Create: Add buttons to copy DAO addresses and logs

### ISSUE THREAD

**Issue by Flash-Git** [dOrgTech/DAOcreator#416]
Adding feature from #376.

> Maybe we have a copy icon in the bottom right that will copy the addresses to the user's clipboard.
Also we'll want a way to export the full deployment log for debugging sake... maybe we combine both of these options into one "popup" menu like it's done in V1: "copy addresses", "copy log"

**Comment by dOrgJelli** [comment]
Copy Logs (bottom right) W/ Hover Tip:
![image](https://user-images.githubusercontent.com/5522128/75115274-cf9cdb00-562a-11ea-8a69-453de0e376c0.png)

Save DAO Addresses Button:
![image](https://user-images.githubusercontent.com/5522128/75115299-070b8780-562b-11ea-9b8b-bc3366069f6d.png)

**Comment by dOrgJelli** [comment]
@pimato please review the styling of these features

**Comment by pimato** [comment]
This def. needs a redesign!

**Comment by pimato** [comment]
can anyone explain me why someone wants to copy an address and about which addresses are we talking about?

**Comment by pimato** [comment]
Also, after a successful deployment, why do we want to let the user deploy it again?

**Comment by Flash-Git** [comment]
> can anyone explain me why someone wants to copy an address and about which addresses are we talking about?

The addresses are the  addresses you get from a deployment: 
```
"Avatar": "0x77Ff0fb79642f9173D26745b104a032e7a596639",
"DAOToken": "0xAA3F1D38928c19a712eDAaaF74cC25eA036B936a",
"Reputation": "0xe64A2EBAC40b47abFB928c591F4C6558d3879954",
"Controller": "0x24B75D747474F1871f7E52F1e097Cf77F42Cb449"
```

> Also, after a successful deployment, why do we want to let the user deploy it again?

So they can change settings and deploy a new one.

**Comment by pimato** [comment]
Those addresses are only important for devs. Normal people really don´t care about those addresses. The daocreator should be as simple af, including feature like that will do the opposite. Alchemy should do the job to let the user know the addresses of each module.

**Comment by pimato** [comment]
Why should the user create a dao, change settings and create a new one ?

**Comment by pimato** [comment]
@dOrgJelli

**Comment by mrrobot16** [comment]
> Why should the user create a dao, change settings and create a new one ?
@pimato 
I think the motivation was that if lets say that you forgot to add another member or something, you are able to go back add such member, and then redeploy.

**Comment by mrrobot16** [comment]
> Why should the user create a dao, change settings and create a new one ?

@pimato @dOrgJelli 
I think the motivation was that if lets say that you forgot to add another member or something, you are able to go back add such member, and then redeploy.

**Comment by dOrgJelli** [comment]
I agree @pimato, copying addresses shouldn't be necessary since they should be able to get to these addresses via Alchemy.

**Comment by Flash-Git** [comment]
Okay, I'll remove the button.
