### ISSUE TITLE
Cotary Create: Load from localstorage bug

### ISSUE THREAD

**Issue by mrrobot16** [dOrgTech/DAOcreator#432]
Whenever orgName or tokenName is equal to "", we should just not display the modal. 

![Screen Shot 2020-02-23 at 7 43 23 PM](https://user-images.githubusercontent.com/761735/75123384-e10ad500-5674-11ea-9e34-9775821a3b35.png)

**Comment by Flash-Git** [comment]
https://github.com/dOrgTech/DAOcreator/pull/435#issuecomment-590281612 
> This highlights that the modal only shows changes made up until the step that the user left at. Not ideal.

**Comment by dOrgJelli** [comment]
Please see how V1 solves this issue. Instead of checking to see if what's loaded is "empty", it never saves an empty form: https://github.com/dOrgTech/DAOcreator/blob/88b42866cbcd2ab91701df9c7bda0d1c854e4e1a/packages/ui_v1/src/components/DAOcreator/index.tsx#L99-L117

**Comment by mrrobot16** [comment]
@dOrgJelli cool this was handle, we still got one more issue that whenever you refresh and data is saved it will show up in the "Review component" but if we hit refresh it will then show blank config and members. 

We are working on it now.

First Refresh (working as expected):
![Screen Shot 2020-02-24 at 3 11 11 PM](https://user-images.githubusercontent.com/761735/75187382-f08f2a00-5717-11ea-8fad-67cc97f7e4fe.png)

Second Refresh(showing blank):
![Screen Shot 2020-02-24 at 3 11 19 PM](https://user-images.githubusercontent.com/761735/75187419-ff75dc80-5717-11ea-92af-b3b90835f641.png)

**Comment by Flash-Git** [comment]
> @dOrgJelli cool this was handle, we still got one more issue that whenever you refresh and data is saved it will show up in the "Review component" but if we hit refresh it will then show blank config and members.
> 

This should be fixed now but the state is getting unnecessarily complex.

**Comment by dOrgJelli** [comment]
> @dOrgJelli cool this was handle, we still got one more issue that whenever you refresh and data is saved it will show up in the "Review component" but if we hit refresh it will then show blank config and members.

Please see version 1, the problem you're describing here was already solved...

**Comment by mrrobot16** [comment]
> @dOrgJelli cool this was handle, we still got one more issue that whenever you refresh and data is saved it will show up in the "Review component" but if we hit refresh it will then show blank config and members.
> 
> We are working on it now.
> 
> First Refresh (working as expected):
> ![Screen Shot 2020-02-24 at 3 11 11 PM](https://user-images.githubusercontent.com/761735/75187382-f08f2a00-5717-11ea-8fad-67cc97f7e4fe.png)
> 
> Second Refresh(showing blank):
> ![Screen Shot 2020-02-24 at 3 11 19 PM](https://user-images.githubusercontent.com/761735/75187419-ff75dc80-5717-11ea-92af-b3b90835f641.png)

This isssue is still persisting.

**Comment by mrrobot16** [comment]
I recently checked and this issue is still persisting.

**Comment by Flash-Git** [comment]
> 
> 
> I recently checked and this issue is still persisting.

It was reintroduced because my code was overwritten by the recent merge. I can fix it tomorrow.

**Comment by mrrobot16** [comment]
@Flash-Git no worries we got it.

**Comment by dOrgJelli** [comment]
Looks great @mrrobot16 @cbrzn, the only other bug with this that I see is that when the user first opens the app & the pop-up opens, the steps go back to where they were, instead of staying at step 1 until the user makes a choice.
