### ISSUE TITLE
Cotary Create: Point a https://daocreator-v2.herokuapp.com to Cotary.io domain

### ISSUE THREAD

**Issue by mrrobot16** [dOrgTech/DAOcreator#461]
@orishim @pimato @dOrgJelli 

Who shall i give access to heroku so we can point heroku app to our cotary domain?

https://devcenter.heroku.com/articles/custom-domains#rules-on-adding-domains

**Comment by dOrgJelli** [comment]
https://launch.dorg.tech/ currently points to the new DAOcreator. In my opinion I think we should hold off on "going public" with Cotary

**Comment by orishim** [comment]
Yup, I think we can close this. I deployed the app to Netlify rather than Heroku and pointed the "launch" subdomain there.
