### ISSUE TITLE
Cotary Create: Change "Minimum DAO Bounty" off default to 0.0000001

### ISSUE THREAD

**Issue by orishim** [dOrgTech/DAOcreator#466]
The contracts don't let us change Minimum DAO Bounty to 0 so currently we have it set to 1 when the user turns this feature off. But that is still 1 GEN downstaked on every proposal. In the old dOrg DAO we had this value set to 5e-8.

This would be improved if we set the DAO downstake to 0.0000001 (1e-8) when the "auto-incentivize curation" option is turned off.

I'm not sure if decimals are supported or how exactly this should be done.

**Comment by dOrgJelli** [comment]
Great catch @orishim! I'll post a PR for this, you can see a DAO with the param change you've suggested here (deployed using the updated DAOcreator): https://alchemy-staging-rinkeby.herokuapp.com/dao/0x40cf615b236c19356d256274226333eb007f3be9/scheme/0xeb4d6a1c2443f6b45087ff0e244d3314818da4bcfb2f2170dc4d65e564822f3d/info/
