### ISSUE TITLE
Cotary Create: Misplaced "x" (Minor formatting bug)

### ISSUE THREAD

**Issue by orishim** [dOrgTech/DAOcreator#467]
<img width="527" alt="Screen Shot 2020-03-05 at 9 38 52 PM" src="https://user-images.githubusercontent.com/10736693/76117141-3e7a1c80-5fb9-11ea-9e25-0a820746cc89.png">

The 'x' ends up in a weird spot after deployment

**Comment by dOrgJelli** [comment]
Fixed in above pr
