### ISSUE TITLE
does kovan support require @daostack/migration rc.41-v4?

### ISSUE THREAD

**Issue by orenyodfat** [dOrgTech/DAOcreator#493]
this version include support for kovan arc rc 33. 
https://github.com/daostack/migration/releases/tag/0.0.1-rc.41-v4

**Comment by dOrgJelli** [comment]
Yes we've added support for the kovan `base` addresses by copying that addresses from that build's `migration.json`.

We do not want to update the migrate-dao.js script as there are risks for run-time errors that way. We'll be upgrading the @daostack/migration dependency with the arc-hives update.
