### ISSUE TITLE
use migration 0.1.1-rc.13-v1 for the experimental daocreator.

### ISSUE THREAD

**Issue by orenyodfat** [dOrgTech/DAOcreator#494]
https://github.com/daostack/migration/releases/tag/0.1.1-rc.13-v1
this will reduce the dao creation transactions to 2 in most of the cases.
(no need to set gp parameters)

**Comment by dOrgJelli** [comment]
Okay will do @orenyodfat. How is this achieved? If there are new VM parameters being used, don't you still have to setParameters on GenesisProtocol if they don't exist on-chain?

**Comment by orenyodfat** [comment]
it is set at the schemes initilise functions.. 
for example see https://github.com/daostack/arc/blob/arc-factory/contracts/schemes/ContributionReward.sol#L102

**Comment by dOrgJelli** [comment]
@orenyodfat I can do this once subgraph's experimental version is updated to use this migration version. If I were to do this now, private network deployments would fail because migration.json addresses would not be present.

**Comment by orenyodfat** [comment]
subgraph is now updated to support it https://github.com/daostack/subgraph/releases/tag/ganache-0.1.1-rc.13-v1-0.1.1-rc.7-v4

**Comment by orenyodfat** [comment]
@dOrgJelli does this already been address ?
