### ISSUE TITLE
Closing MetaMask Popup Should Do Something

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/DAOcreator#50]
Currently the user has to know to look at their metamask icon on the top right if they accidentally close the popup. We can't tell if they close the popup; because ethereum.enable() doesn't return.

Instead what we can do is if we've waited a few seconds and they haven't clicked anything, we can show an icon that points to their metamask location in the top right. Or have some glowing effect coming from that corner.

**Comment by orishim** [comment]
Is this still an issue with the move to migration repo?

**Comment by orishim** [comment]
Subsumed under [200](https://github.com/dOrgTech/DAOcreator/issues/200)
