### ISSUE TITLE
wrong link in alchemy xdai 

### ISSUE THREAD

**Issue by orenyodfat** [dOrgTech/DAOcreator#509]
see https://github.com/daostack/alchemy/issues/1948

How about enable  dao creator to get params ,such as these links, as part of its init params  ?
These params , if exist will override its default params.
This way we can control it via alchemy and no need new version for each twick .

**Comment by cbrzn** [comment]
Yup! Note that this change will need to be made in both the master/dev and experimental branches separately

**Comment by orenyodfat** [comment]
> Yup! Note that this change will need to be made in both the master/dev and experimental branches separately
 lets do in experimental .

**Comment by orenyodfat** [comment]
@cbrzn can you please do that for none experimental.( alchemy 1.0) ?

**Comment by cbrzn** [comment]
@orenyodfat sure
