### ISSUE TITLE
DAO Creator x TestNet

### ISSUE THREAD

**Issue by anthonymq** [dOrgTech/DAOcreator#516]
Hi,
I tried to deploy a DAO on Ropsten, everything was fine until I clicked on "Open Alchemy". My DAO is not found.
[created dao](https://launch.dorg.tech/dao/0x3c74e21DEd47706C5Df451f34aCfa4D41A487F6c)
Is there a Ropsten Alchemy or another Testnet ?
Thanks

**Comment by cbrzn** [comment]
Hello @anthonymq! Currently we are supporting rinkeby, xdai or mainnet! Just change your metamask provider to rinkeby and it will deploy to that testnet

**Comment by anthonymq** [comment]
I found https://alchemy-staging-kovan.herokuapp.com/daos/create by digging.
But I'm encountering a bug while trying to redeem my REP after a successful proposition. I asked DaoStack for support.
