### ISSUE TITLE
grammer on v 1.0.19 

### ISSUE THREAD

**Issue by orenyodfat** [dOrgTech/DAOcreator#526]
related to #524 
for the case there is one network to swith to,,, is should be : “Switch network to deploy in xdai” / not “networks” ..

<img width="291" alt="Screen Shot 2020-12-06 at 10 22 15" src="https://user-images.githubusercontent.com/5994398/101275371-c17d0d00-37ad-11eb-95e6-b5779f7c3b42.png">

**Comment by cbrzn** [comment]
Has been addressed on #524
