### ISSUE TITLE
Integrate feedback form

### ISSUE THREAD

**Issue by orishim** [dOrgTech/DAOcreator#58]
Add an link to the (google) feedback form on the landing page. 

https://docs.google.com/forms/d/1qMwTYMFpLW0KU8l9dnHkhixwhz-fo5Qtqumjg_7JZ80/

A next step could be to create a form for feedback directly in the dapp. If implemented as its own React component, this ‘feedback module’ could be a standard part of the governance library.

**Comment by oshimony** [comment]
alternative would be to integrate a simple feedback form in the app itself

like [this](https://beta.cent.co/feedback)
<img width="862" alt="screen shot 2019-02-06 at 5 10 37 pm" src="https://user-images.githubusercontent.com/10736693/52377195-26d90900-2a32-11e9-83f5-c1b88ff45c21.png">

or this (google sheets):
![feedback](https://user-images.githubusercontent.com/10736693/52377235-47a15e80-2a32-11e9-9140-e338f3a1ab3f.png)
