### ISSUE TITLE
Build "Templates Configuration" View

### ISSUE THREAD

**Issue by gh1dra** [dOrgTech/DAOcreator#6]
**Acceptance Criteria**
As I user I would like to be able to select a governance template from a drop down list. It should describe to me the schemas, voting mechanisms for proposals, and global constraints implemented by default in the contract.

There should be a button to create a new template. A place to configure permissions and roles. Links to more information should also be made available

**Mock**
<img width="1350" alt="screen shot 2018-11-11 at 8 47 26 pm" src="https://user-images.githubusercontent.com/7246942/48321953-165ff080-e5f3-11e8-9ab6-14cbc80a1141.png">

**Comment by gh1dra** [comment]
It might be worth hardcoding some of these templates that the user can select during the features step in case they don't want to go through setting up the voting machine for each scheme

**Comment by dOrgJelli** [comment]
Replaced with https://github.com/dOrgTech/DAOcreator/issues/187
