### ISSUE TITLE
Add the Generic Scheme?

### ISSUE THREAD

**Issue by sogasg** [dOrgTech/DAOcreator#73]
If it is supported by Alchemy Earth. Is it?

Add the Scheme here: https://github.com/dOrgTech/DAOcreator/blob/faedbcc49c0c3fcc6afb6b47f66636e6c8573763/src/lib/integrations/daoStack/arc/schemes.ts#L4

Add the Scheme to the UI Wizard here: https://github.com/dOrgTech/DAOcreator/blob/faedbcc49c0c3fcc6afb6b47f66636e6c8573763/src/components/pages/DAOcreator/index.tsx#L36

**Comment by gh1dra** [comment]
@sogasg it should be supported by alchemy earth !!

**Comment by gh1dra** [comment]
So we've decided not to support this in DAOCreator for the reasons of that a user should be able to vote to add this scheme with a particular contract address rather than specifying one upon initialization.
