### ISSUE TITLE
Create new UX and styles for the SchemeStep (features) page

### ISSUE THREAD

**Issue by gh1dra** [dOrgTech/DAOcreator#75]
Currently, we just stack each of the feature steps on top of each other but we should have a more unified design.

We should also validate the voting parameters being provided for each scheme.

Initial thoughts: let's only allow the user to decide one type of voting machine for all schemes. So instead the view would have the form that exists now, but a checklist of schemes they can select from with their descriptions

**Comment by sogasg** [comment]
We have an issue for the voting parameters here: #26.

The reason for letting the user select a voting machine per scheme is the way Alchemy Erth lays out the schemes (check this: https://www.youtube.com/watch?v=h40NZ_9hCr4&feature=youtu.be&t=900). Out from what I see there, it seems that each Scheme is its own separate "thing" and therefore I think it should be possible to select a voting machine per scheme. Also, some schemes have inputs besides the voting machine input, for instance, ContributionReward (see #72).

Also, I think it makes sense for a DAO to have different parameters for a voting machine that is governing mission critical things then for other schemes that might not need to be that "tightly controlled". For instance, voting in a DAO norm (https://daotalk.org/t/detecting-bad-proposals/441) vs. updating to a new DAO controller contract address or something. So even if only the GenesisProtocoll was supported I think it makes sense to let the user configure it differently for each scheme.

But from a usability perspective, I think it makes sense to maybe default to selecting and configuration one voting machine for everything. But then I think we must give the user the option to select "advanced mode" if the user wants to set up voting machines individually.

We must also remember to "force" the user to create an Alchemy Erth compatible DAO. So if a scheme is required for Alchemy Earth the user should not be able to unselect it and the other way around.

**Comment by sogasg** [comment]
After the talk with DAOstack, I think what we need to accomplish is:

1. Letting the user select the schemes to be added.
2. Letting the user specify parameters for each scheme, 1.) including voting machine and 2.) voting machine parameters, in addition to 3-?.) other scheme parameters (like the address of the contract to call for the generic scheme, etc.).

What complicates this a little bit is that the user should be able to add multiple generic schemes (one for each contract that the DAO should be able to call).

I think we need to create some wireframes for the UI/UX for this process before we proceed (perhaps you want to take a look at this @ontologymachine ).

**Comment by dOrgJelli** [comment]
My thoughts:
- I think we should support a different voting machine per Scheme.
- We should support the Scheme parameters (inputs).
- I agree, all this "advanced" configuration should be hidden from new / uninterested users.
- We should have a large warning sign if the user does something that makes their DAO incompatible w/ Alchemy Earth.
- I like the UX you described in your latest comment @sogasg

**Comment by sogasg** [comment]
Thanks for your input :)

My understanding from the talk with DAOstack was that we could think of everything in Arc as supported by Alchemy (or soon to be).
